export enum SubmissionAcknowledge {
  USER_FILTER_ERROR,
  DJATY_CRASH_REPORT_SENT,
  BUG_REPORTED,
  FRONTEND_LINKING_TEMP_BUG_REPORTED,
  DJATY_CRASH_REPORT_DISABLED,
  SKIPPED_NESTED_USER_DOMAIN,
  SKIPPED_DJATY_TRACKING_DISABLED,
  SKIPPED_DJATY_EXTENSION_NOT_DETECTED,
}
